### ISSUE TITLE
blankplanet.cfg gets "touched" after server shutdown

### ISSUE THREAD

**Issue by TheQuadShot** [MJRLegends/BlankPlanet#2]
_touch_ - change file access and modification times
My editor gives me a warning that the file has changed, however the only change I can find is the timestamp. Sorry if this is normal, it just doesn't make sense to me why it should/does.

Minecraft 1.12.2
Forge 14.23.3.2698

BlankPlanet-0.1-1.12.2.jar

Galacticraft-Planets-1.12.2-4.0.1.176.jar
GalacticraftCore-1.12.2-4.0.1.176.jar
MicdoodleCore-1.12.2-4.0.1.176.jar

GalacticraftTweaker-1.12.2-1.0.1.jar
Complete Mod List: https://pastebin.com/cH4n9YAp

**Comment by MJRLegends** [comment]
This isnt something thats a bug
