### ISSUE TITLE
[1.12] Can't travel to and from the blank planet via rocket

### ISSUE THREAD

**Issue by MasterEnderman** [MJRLegends/BlankPlanet#3]
I'm unable to travel to or from the blank planet using a rocket, but i don't want to use the teleporter block. If i place down a rocket in the "blank planet" dimension, press the "spacebar" to launch. and after i reach the galaxy map i can't select a destination, because no plantes are shown. (see screenshot) If i launch a rocket from another planet I'm unable to find the "blank planet" in the galaxy map.

Forge: 14.23.4.2739
MicDoodleCore: 4.0.1-181
Galacticraft: 4.0.1-181
GalacticraftPlanets: 4.0.1-181
MJRLegends Lib: 1.1.5
Extra Planets: 0.4.1
PlanetProgression: 0.2.5
Blank Planet: 0.1

Config: (there is a typo in the "required rocket tier" section by default)
```
# Configuration file

"advanced spawn options" {
    S:"Number ID of Dimesnion for 'First/Everytime join world options'"=0
    S:"Number ID of Dimesnion for 'Teleport Player on Death' option"=0
    B:"Teleport Player on Death (skip bed spawns)"=false
    B:"Teleport Player on everytime they join world"=false
    B:"Teleport Player only when they first join the world"=false
}


"dimension options" {
    S:"Biome id"=199
    S:"Biome name"=BlackHole
    S:"Dimension id"=-99
    B:"Make Landing Platforms"=true
}


general {
    B:"Spawn Parachest on Teleport"=true
    S:"Teleporter SpawnX"=0
    S:"Teleporter SpawnY"=100
    S:"Teleporter SpawnZ"=0
    S:"Teleporter Xp amount"=1
    B:"Teleporter reqiures Xp"=false
}


"world options" {
    B:"Always Day Time"=false

    # WILL GET IGNORED IF 'Always Daytime' IS ENABLED
    B:"Always Night Time"=true
    B:"Breathable Atmosphere"=true
    S:"Day Length"=24000
    S:"Fall Damage Multiplier"=0.3
    S:"Fuel Usage Multiplier"=1.0
    S:Gravity=0.058
    S:"Rocket reqiured"=10
    S:"Solar Energy Multiplier"=8.0
    S:"Sound Vol Reduction"=10.0
    S:"Star Brightness"=1.0
    S:"Thermal Level Multiplier"=0.0
    S:"Wind Level"=0.0
}
```
Galaxy Map (trying traveling to the "black hole")
![image](https://user-images.githubusercontent.com/24524662/43367953-8d835cb0-9355-11e8-9faa-41a31539a576.png)
Galaxy Map (trying traveling from the "black hole")
![image](https://user-images.githubusercontent.com/24524662/43368013-4e5407e6-9356-11e8-97ea-3c63e0e266e8.png)

For clearification i used the planet progression command to unlock all planets, so this isn't the issue.

**Comment by MasterEnderman** [comment]
A quick addition after creating a new world and using the unlock command from planet progression, the black hole now shows up in the galaxy map and traveling to it works as well, but I'm unable to travel from it again.

**Comment by MJRLegends** [comment]
Sorry for the delay im looking at this issue atm, think i know the issue.

**Comment by MJRLegends** [comment]
Update has been uploaded to curseforge to fix this. will be showing soon
