### ISSUE TITLE
[1.12] Unable to travel from the Black Hole to another Planet

### ISSUE THREAD

**Issue by MasterEnderman** [MJRLegends/BlankPlanet#4]
### ---Issue Report---
First of all thank you for the last update. I really appreciate that.

### Description of Issue
You can't travel from the Black Hole Dimension to another, because of the broken Galaxy Map.

### Steps to Reproduce Issue
1. go to the black hole dimension
2. open the galaxy map

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/24524662/43675626-7a606b4a-97e3-11e8-8903-a859d48e0147.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Forge: 14.23.4.2745
MicDoodleCore: 4.0.1-181
Galacticraft: 4.0.1-181
GalacticraftPlanets: 4.0.1-181
MJRLegends Lib: 1.1.5
Extra Planets: 0.4.1
PlanetProgression: 0.2.5
Blank Planet: 0.2

**Where did this bug happen:** [Single Player or Server]
Singleplayer

### Additional Information

I used the unlock command from planetprogression before traveling to the black hole.

**Comment by MJRLegends** [comment]
It worked in my testing environment.

**Comment by MJRLegends** [comment]
Plesse provide more details as i csnt reproduce the issue

**Comment by MasterEnderman** [comment]
so what are details you need to know? I mean the galaxy map is broken when you open it in the blankplanet dimension.

**Comment by MJRLegends** [comment]
Client/Server logs would be a great help

**Comment by MasterEnderman** [comment]
https://pastebin.com/7z2RiQxh here it is but it doesn't mention galacticraft or blankplanet anywhere.

**Comment by MJRLegends** [comment]
@MasterEnderman please include the full logs, including the fml one

**Comment by MasterEnderman** [comment]
I think you fixed the problem already.
https://github.com/MJRLegends/Planet-Progression/issues/35

Didn't tested it yet, but will soon.

**Comment by MJRLegends** [comment]
Ok nice
